services:
  postgres:
    image: postgres:16
    container_name: traiviu-postgres
    restart: "no"
    environment:
      POSTGRES_DB: traiviu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iaruni
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traiviu-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traiviu-backend
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/traiviu
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: iaruni
      APP_UPLOAD_DIR: /app/uploads
      APP_PUBLIC_BASE_URL: "http://192.168.7.155:8000"
      ALLOWED_ORIGINS: "https://localhost,http://localhost,http://localhost:8100,http://localhost:4200,https://ivani26.iesmontenaranco.com"
    ports:
      - "8000:8085"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - traiviu-network

volumes:
  postgres_data:

networks:
  traiviu-network:
    driver: bridge