spring.application.name=traiviu-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/traiviu
spring.datasource.username=postgres
spring.datasource.password=iaruni

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8085

app.jwt.secret=dGhpc19pc19hX3ZlcnlfbG9uZ19zZWNyZXQxMjM0NTY=
app.jwt.expiration=86400000